GET http://34.107.121.20:8080/api/students/
Content-Type: application/json
token: 9ACrw84fWdOsQDwUcVGP

###

// Create student
POST http://localhost:8080/api/students/
Content-Type: application/json
token: ViOpt2rXjoqHcKA8BJeD

{
  "passedExam": "DIDNT_PASS",
  "subjectOrientation": {
    "id": "4d3cd0ab-75b4-4753-aff1-35006c69cee7"
  }
}

###

// Update student
PUT http://34.107.121.20:8080/api/students/
Content-Type: application/json
token: 2UXI5tUiQmJ5NslBjAIA

{
  "id": "6f8188b1-6bf1-47b9-87b2-a4f3d11c36b5",
  "subjectOrientation": {
  "id": "e1265563-4d42-4299-80e1-16c6f31f0ee2"
  },
  "grades": [0,0]
}

###

DELETE http://localhost:8080/api/students/
Content-Type: application/json
token: ViOpt2rXjoqHcKA8BJeD

{
  "id": "65bb969d-bbe0-4788-b329-433d0b1a9d22"
}

###
