// Delete example
DELETE http://localhost:8080/api/subjectOrientations
Content-Type: application/json
token: ViOpt2rXjoqHcKA8BJeD

{
  "id": "fd2ef40c-1908-46be-aaa9-9b119aac9a0c"
}

###
// Example for when a teacher tries to delete a different teacher's orientation
DELETE http://localhost:8080/api/subjectOrientations
Content-Type: application/json
token: gEbbFi3BWQjtHbKDlZud

{
  "id": "c6e98d19-b222-4528-baf8-66472aa85f97"
}

###
// Example of getting the user's orientations
GET http://localhost:8080/api/subjectOrientations
Content-Type: application/json
token: ViOpt2rXjoqHcKA8BJeD

###
// Update an orientation
PUT http://localhost:8080/api/subjectOrientations
Content-Type: application/json
token: ViOpt2rXjoqHcKA8BJeD

{
  "shortName": "ПМБ",
  "subjects": [
    "Makedonski jazik",
    "Germanski jazik"
  ]
}

###

// Create an orientation (only shortName is mandatory), also, copies are blocked (except in a special case) and if
// the orientation already exists, it finds it, and makes a copy of it, instead of just sending a relation to the class
POST http://localhost:8080/api/subjectOrientations
Content-Type: application/json
token: ViOpt2rXjoqHcKA8BJeD

{
  "shortName": "ПМG"
}

###
// Previously mentioned special case (that should be fixed)
POST http://localhost:8080/api/subjectOrientations
Content-Type: application/json
token: ViOpt2rXjoqHcKA8BJeD

{
}

###