package com.svedprint.main.exceptions;

public enum SvedPrintExceptionType {
    NO_CLASS_ASSIGNED,
    NO_SCHOOL_ASSIGNED,
    NO_USERNAME_PROVIDED,
    DIRECTOR_NAME_MISSING,
    NO_USER_PROVIDED,
    MISSING_CLASS_NAME,
    NO_YEAR_PROVIDED,
    UNSUPPORTED_FUNCIONALITY,
    NO_ORIENTATION_PROVIDED
}
